version: "3.8"

services:
  app:
    build: .
    container_name: app
    volumes:
      - .:/app
    environment:
      - PATH_TO_FILE=${PATH_TO_FILE:-"main.py"}
      - GIT_PYTHON_REFRESH=quiet
    env_file:
      - .env
    entrypoint: ["python", "${PATH_TO_FILE}"]
